### ISSUE TITLE
 Error: executing a cancelled action

### ISSUE THREAD

**Issue by dankerk** [mjhea0/cypress-visual-regression#101]
When I try to run the command to take the base screenshots or when I just run cypress it throws this error:

(./node_modules/.bin/cypress run --env type=base --config screenshotsFolder=cypress/snapshots/base)

```
Error: executing a cancelled action
      at AsyncAction.__webpack_modules__.2817.AsyncAction.execute (http://localhost:9000/assets/scripts/my-page.bundle.js:3010:20)
      at AsyncScheduler.__webpack_modules__.2817.AsyncScheduler.flush (http://localhost:9000/assets/scripts/my-page.bundle.js:3122:32)
      at i (http://localhost:9000/my-page.html:4:1401)
      at http://localhost:9000/my-page.html:4:2171
      at Array.forEach (<anonymous>)
      at $Cypress.pause (http://localhost:9000/my-page.html:4:2088)
```

from my package.json:
    "cypress": "^8.3.1",
    "cypress-visual-regression": "^1.6.1",

I used the exact steps from the readme and it does in fact take the screenshots, but the test fails.

  it('should display the car compose page correctly', () => {
    cy.visit('http://localhost:9000/my-page');
    cy.compareSnapshot('my-page', 0.5);
  });

Any idea on if this is an issue with this package or with something else?

**Comment by mjhea0** [comment]
Are you using this project?

https://github.com/Terrycoco/react-cypress-boilerplate/blob/master/node_modules/rxjs/src/internal/scheduler/AsyncAction.ts#L93

**Comment by dankerk** [comment]
No I'm not, but it turns out visual regression works fine on some other pages that don't use rxjs. So it's most likely nothing wrong with this package. I'll dig into it some more. Thanks!

**Comment by dankerk** [comment]
It turns out the culprit originated from using the rxjs operator debounceTime. Because Cypress stops the execution of things on the page at some point, the last value emitted from the observable has been cancelled before it could get past the debounceTime operator. This is why it didn't occur to normal users of the page. Changing debounceTime for throttleTime worked as throttleTime emits a value directly.
