### ISSUE TITLE
dump a base64-encoded diff to console on fail?

### ISSUE THREAD

**Issue by k4y4k** [mjhea0/cypress-visual-regression#104]
Hey 👋

I really like this as an alternative to something like `cypress-image-snapshot`.

That said, however, I am (sorely) missing a feature.

Would it be possible to dump a base64-encoded image string to the console on test fail? I don't have the infrastructure to upload or cache a diff image, but copy/pasting a string from the logs is easy peasy.

I'm willing to throw together a PR if someone could kindly point me where to start?

Cheers!

**Comment by mjhea0** [comment]
HI @k4y4k, 

I think that's a great idea. You could probably add that logic to the following if statement:

https://github.com/mjhea0/cypress-visual-regression/blob/master/src/command.js#L60-L63

Does that help?

**Comment by k4y4k** [comment]
Hello again 😄👋

Sure, that helps. I'll take a look and throw together something soon.
