### ISSUE TITLE
Feature: generate diff image only on failed tests

### ISSUE THREAD

**Issue by Zaista** [mjhea0/cypress-visual-regression#108]
Not sure if this is a way to go regarding new feature request, but here it goes:

Currently diff images are generated and saved for all tests no matter if they fail or not.
Usually you wouldn't care about successful tests, so the implementation could be changed to just save images for failed tests.
Or to have a flag at least to switch between the two behaviors.

I checked the plugin, and I don't think there's anything to support this yet.

**Comment by mjhea0** [comment]
This is a great idea. Want to run with it?

**Comment by Zaista** [comment]
I can create a PR tomorrow

**Comment by clmntrss** [comment]
@mjhea0 Hi, any update about the PR ?
