### ISSUE TITLE
Make base and actual in the same test

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [mjhea0/cypress-visual-regression#109]
Currently I am experiencing layout difference after some interaction when expansion panels are open and closed and I want to find out what is wrong. so I would take a screenshot before this happens and after to see the difference. Is that possible?

**Comment by mjhea0** [comment]
You can use `screenshot` for that sort of debugging.  https://docs.cypress.io/api/commands/screenshot#Arguments

**Comment by sschneider-ihre-pvs** [comment]
how would I do that? there is no diff option as far as I can see.
