### ISSUE TITLE
Error on tsconfig.json - Cannot find type definition file for 'cypress-visual-regression'.

### ISSUE THREAD

**Issue by ChiuWeiBin** [mjhea0/cypress-visual-regression#120]
**However I am able to use the plugin and seems no problem, any ways to suppress the error?**

```
Cannot find type definition file for 'cypress-visual-regression'.
  The file is in the program because:
    Entry point of type library 'cypress-visual-regression' specified in compilerOptionsts
```

![image](https://user-images.githubusercontent.com/65437899/158725948-369712a7-9958-40d3-931f-9324451b5512.png)

**Comment by MrRahulR** [comment]
I'm using this with TypeScript and tbh I faced the same problem but I removed it from `tconfig.json` and still, my code is working properly for visual regression. If you need you can give it a try or maybe like everyone say...

```
If it's working, Don't touch it!
```

**Comment by Josh68** [comment]
From what I've read, I think this might be resolved by building in `/dist` as `index.d.ts` rather than `command.d.ts`. I'm also including in my `types` `cypress-axe`, and I get no complaint for that plugin which exports `/dist/index.d.ts`.
