### ISSUE TITLE
Problem running with the Cypress runner

### ISSUE THREAD

**Issue by DamienCassou** [mjhea0/cypress-visual-regression#124]
Hi,

I face no problem with this plugin when using `cypress run`. But, if I use `cypress open`, then either the command never fails (when using the configuration in the plugin's README) or it always fail (when adding `{"env": {"type":"actual"}}` in cypress.json). In the latter case, the comparison fails because the 2 pictures are of different resolutions (even though the test itself specifies a viewport height and width).

Is the Cypress Runner GUI supported?

**Comment by mjhea0** [comment]
No, the Cypress Runner GUI is not supported unfortunately.

**Comment by randomVariable2000** [comment]
@DamienCassou Maybe you need this https://docs.cypress.io/api/plugins/browser-launch-api#Set-screen-size-when-running-headless.

**Comment by rockResolve** [comment]
Actually this is quite doable. Need to:

1. Set (ScreenShot option) overwrite to true
Needed to avoid GUI rerunning test and generating new files with suffix - while the compare ignores them and only ever uses the first file generated.
2. Check current viewport width against the viewport width used when generated (maybe headless screen size?).  Note only need to check height if capture: fullPage (normal default) isnt used.
3. If the viewport isnt enough (e.g. running the GUI on a small laptop?), then log a warning, and set the errorThreshold to 100%.

You probably want to set "ALWAYS_GENERATE_DIFF": true, so successful diffs remove previous failed diffs
