### ISSUE TITLE
Is this a dev dependency?

### ISSUE THREAD

**Issue by Josh68** [mjhea0/cypress-visual-regression#127]
Simple question. Instructions say to `npm install cypress-visual-regression` (no `--save-dev`)

Thanks, and thanks for making this tool.

**Comment by Zaista** [comment]
This is mostly your preference and how you want the npm installation to behave on production servers, but since this is a testing plugin, you most likely want it installed with --save-dev

**Comment by Josh68** [comment]
Thank you.
