### ISSUE TITLE
Running regression throwing errors

### ISSUE THREAD

**Issue by mikeruddy** [mjhea0/cypress-visual-regression#13]
1) Navigation screenshot home screen:
     CypressError: cy.task('compareSnapshotsPlugin') failed with the following error:

> Error: ENOENT: no such file or directory, mkdir '/Users/me/Documents/app/cypress/snapshots/diff/visualregression/navigation.spec.js'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Promise (/Users/me/Documents/app/node_modules/cypress-visual-regression/dist/plugin.js:25:10)

**Comment by mjhea0** [comment]
That means that directory does not exist. Set the path to your snapshots folder in the `screenshotsFolder` config.

command line example:

```sh
$ ./node_modules/.bin/cypress run --env type=base --config screenshotsFolder=cypress/snapshots/base
```

config file example:

```json
{
  "screenshotsFolder": "cypress/snapshots/actual",
  "trashAssetsBeforeRuns": true,
  "video": false
}
```

**Comment by mikeruddy** [comment]
I have that in my config. The error happens when I run `./node_modules/.bin/cypress run --env type=actual`. I see the screenshots in the baseline and actual directory, but the diff folder stays empty. I also get this warning text early on:

> Warning: We failed to trash the existing run results. This error will not alter the exit code.

I'm using node v10.16.0 if that matters.

Here's what I put in my package.json run section

> "cypress:baseline": "cypress run --env type=base --config screenshotsFolder=cypress/snapshots/base",
    "cypress:compare": "cypress run --env type=actual",

**Comment by mjhea0** [comment]
Does this directory exist - "/Users/me/Documents/fos_ncui/cypress/snapshots/diff/?

That's the directory that you specified.

**Comment by mikeruddy** [comment]
/cypress/snapshots/diff/

It exists but it's empty. I noticed in your docker setup your files are slightly different. I wonder if that's contributing.

https://github.com/mjhea0/cypress-visual-regression/blob/master/docker/cypress/support/commands.js

**Comment by mjhea0** [comment]
probably related to this error: https://github.com/mjhea0/cypress-visual-regression/issues/9

what kind of machine are you running?

**Comment by mikeruddy** [comment]
I'm on OSX 10.14

**Comment by mjhea0** [comment]
@mikeruddy I just made [some changes](https://github.com/mjhea0/cypress-visual-regression/pull/14). Can you install version 1.0.3 and try running it again?

**Comment by mikeruddy** [comment]
So it seems to output to the diff directory with a screenshot that's grayed out. The rest of the errors may be on my end. 

> Warning: We failed to trash the existing run results.

> This error will not alter the exit code.

> Error: Command failed: /Users/me/Library/Caches/Cypress/3.3.2/Cypress.app/Contents/Resources/app/packages/server/node_modules/trash/lib/macos-trash /Users/me/Documents/app/cypress/videos/visualregression
“visualregression” couldn’t be moved to the trash.

    at ChildProcess.exithandler (child_process.js:287:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)


>  0 passing (14s)
 >  1 failing

  > 1) Navigation screenshot home screen:
  >    CypressError: Timed out retrying: Expected to find content: 'Close' but never did.


This may be because I'm never ending the test.

**Comment by mikeruddy** [comment]
> [63495:0702/130554.435708:ERROR:gles2_cmd_decoder.cc(4439)] [.RenderWorker-0x7ff44d84c800.GpuRasterization]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete
[63495:0702/130554.435744:ERROR:gles2_cmd_decoder.cc(4439)] [.RenderWorker-0x7ff44d84c800.GpuRasterization]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawElements: framebuffer incomplete
[63495:0702/130554.435762:ERROR:gles2_cmd_decoder.cc(4439)] [.RenderWorker-0x7ff44d84c800.GpuRasterization]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete
[63495:0702/130554.435788:ERROR:gles2_cmd_decoder.cc(4439)] [.RenderWorker-0x7ff44d84c800.GpuRasterization]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawElements: framebuffer incomplete

Also I'm getting a bunch of console output like this after the test finished. Thought it could be related to the video features but I have that disabled in my settings.

**Comment by mjhea0** [comment]
Closing. Please re-open if it's still an issue.
