### ISSUE TITLE
Screenshots of long pages with modal are incorrect

### ISSUE THREAD

**Issue by jdvegmond** [mjhea0/cypress-visual-regression#15]
![Step2InformationPopup-base](https://user-images.githubusercontent.com/32638636/61110383-757a4b80-a487-11e9-83d7-8e1b57cedef8.png)

As can be seen in the attached screenshot, snapshots of long page with a modal show the modal multiple times. I think this should not happen.

**Comment by mjhea0** [comment]
The screenshot functionality comes from Cypress itself. You will have to open an issue with them directly. https://github.com/cypress-io/cypress/issues/2584 may be related.
