### ISSUE TITLE
CypressError: cy.task('compareSnapshotsPlugin') failed with the following error:

### ISSUE THREAD

**Issue by solomono10** [mjhea0/cypress-visual-regression#17]
Running ` ./node_modules/.bin/cypress run --env type=base --config screenshotsFolder=cypress/snapshots/base` is fine but...

I am getting this error after running `./node_modules/.bin/cypress run --env type=actual`

`
CypressError: cy.task('compareSnapshotsPlugin') failed with the following error:

The 'task' event has not been registered in the plugins file. You must register it before using cy.task()

Fix this in your plugins file here:
cypress/plugins/index.js

https://on.cypress.io/api/task
`

### cypress/support/commands.js

`
const compareSnapshotCommand = require('cypress-visual-regression/dist/command');
compareSnapshotCommand();
`

### cypress/plugins/index.js

`
const getCompareSnapshotsPlugin = require('cypress-visual-regression/dist/plugin');
module.exports = on => {
  getCompareSnapshotsPlugin(on);
};
`

### /.d.ts
`
declare module 'cypress-visual-regression/dist/plugin';
`

### /cypress.json
`
{
  "screenshotsFolder": "cypress/snapshots/actual",
  "trashAssetsBeforeRuns": true
}
`

**Comment by Renaud009** [comment]
@solomono10 How did you resolve this?

**Comment by lasithdilshan20** [comment]
Hi ,

I have a same issue.

CypressError
cy.task('rp_screenshot') failed with the following error:

The task 'rp_screenshot' was not handled in the plugins file. The following tasks are registered: compareSnapshotsPlugin, copyScreenshot, generateReport
