### ISSUE TITLE
Is there a way to change the threshold? 

### ISSUE THREAD

**Issue by helmutgranda** [mjhea0/cypress-visual-regression#18]
I have an error message which color it is #d73a0f, for testing purposes I changed that to plain "purple", however Cypress is considering those colors the same giving me a false positive:

![image](https://user-images.githubusercontent.com/82293/65463949-5c463180-de1e-11e9-9d9e-bf49c441ef12.png)

Is there a way to improve that?

**Comment by mjhea0** [comment]
Yes, you can enter an optional threshold as stated in the readme:

https://github.com/mjhea0/cypress-visual-regression#to-use

Out of curiosity, I added an additional test case for your scenario: https://github.com/mjhea0/cypress-visual-regression/blob/master/docker/cypress/integration/main.spec.js#L47

Hope that helps!

**Comment by helmutgranda** [comment]
It does help! Thanks so much for going the extra mile and creating an example, I remember I had seen some of this information and I was sure it was missing but I was wrong.

Is there a way to create a base and actual for each one of my tests without me having to create a ```compareSnapshot``` function? I guess being explicit on when a test is needed is better. However, since we do a lot of UI it may speed things up to create a visual test for each one of our functional tests. Just a thought and this may already be implemented.

**Comment by mjhea0** [comment]
I built out a more robust version of the visual regression library that works behind the scenes implicitly, similar to how you describe. However, this was for a commercial product that I am not ~able~ allowed to open source at this time.
