### ISSUE TITLE
Upgrade to Cypress 4.02

### ISSUE THREAD

**Issue by 3590Duncan** [mjhea0/cypress-visual-regression#21]
Hello, we are attempting to upgrade our CI to Cypress 4.0.2 but are being blocked because we are using the Visual Testing plug in. There seems to be a hard cap on using version 3.X.X with this plug in, Can you confirm we are able to have the dependancy upgraded to version 4? We have confirmed our visual tests pass on version 4.0.2

Thanks

**Comment by mjhea0** [comment]
Just upgraded: https://github.com/mjhea0/cypress-visual-regression/pull/22
