### ISSUE TITLE
Error threshold description is contradictory

### ISSUE THREAD

**Issue by vvanpo** [mjhea0/cypress-visual-regression#23]
https://github.com/mjhea0/cypress-visual-regression#to-use

> Value can range from 0.00 (no difference) to 1.00 (every pixel is different). So, if you enter an error threshold of 0.50, the test would fail only if 0.51 percent of pixels are different.

If 1.00 means every pixel is different, that means 100%. In which case 0.50 would imply 50% of pixels, not 0.51%.

**Comment by mjhea0** [comment]
@vvanpo thanks for bringing this to my attention.

Does this wording suffice:

Value can range from 0.00 (no difference) to 1.00 (every pixel is different). So, if you enter an error threshold of 0.51, the test would fail only if > 51% of pixels are different.

More examples:

| Threshold | Fails when |
|-----------|------------|
| .25 | > 25%  |
| .30 | > 30% |
| .50 | > 50% |
| .75 | > 75% |

**Comment by vvanpo** [comment]
@mjhea0 Yep, that clears up the ambiguity.

**Comment by mjhea0** [comment]
Updated https://github.com/mjhea0/cypress-visual-regression/pull/24
