### ISSUE TITLE
ssh connection error

### ISSUE THREAD

**Issue by nweiser1** [mjhea0/cypress-visual-regression#29]
running this
npm install cypress-visual-regression --save-dev
getting this:
Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/cypress-io/request.git
npm ERR!
npm ERR! ssh: connect to host github.com port 22: Connection timed out
npm ERR! fatal: Could not read from remote repository.

I am able to  install other things just fine. any ideas? on windows.

**Comment by mjhea0** [comment]
Not sure. Does [this](https://github.com/cypress-io/cypress/issues/6751) help?
