### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by mjhea0** [mjhea0/cypress-visual-regression#30]
Found by @ kane77:

> While doing the tests I noticed that in plugin.js the percentage is initialized to 0. In case the screenshot sizes are different it throws error and returns percentage 0 so it will pass. is that expected behavior?

https://github.com/mjhea0/cypress-visual-regression/pull/28#issuecomment-602525325

**Comment by Gbuomprisco** [comment]
I think I am encountering this issue. 

Something I haven't been able to understand is why my images are created with different sizes during the actual vs base runs. As a result, the library throws an error (although the tests do not fail).

**Comment by mjhea0** [comment]
Thanks for your feedback, @Gbuomprisco.

What do you think the expected behavior should be in this situation?

**Comment by Gbuomprisco** [comment]
@mjhea0 I actually think the problem I encountered was related to Cypress and not this plugin specifically - I had to set a fixed viewport (but while headless they keep getting taken at a different resolution).

**Comment by mjhea0** [comment]
Ok. I'm going to close this then. Please re-open if you come across it again. Cheers!
