### ISSUE TITLE
Should fail when images are of different sizes

### ISSUE THREAD

**Issue by rslemos** [mjhea0/cypress-visual-regression#37]
The test should fail if base and actual images have different dimensions.

Currently, cypress-visual-regression just logs a message:

```
Error: Image sizes do not match.
    at pixelmatch (/home/.../node_modules/pixelmatch/index.js:20:15)
    at compareSnapshotsPlugin (/home/.../node_modules/cypress-visual-regression/dist/plugin.js:70:24)
    ✓ 375x667 (10081ms)
```

The test pass though.
*At the very least* the test should fail.
*At best*, the smallest image should be extended (transparent canvas?) before comparison, so we can inspect where elements have gone astray.

**Comment by mjhea0** [comment]
So, why are the actual images a different size?

**Comment by rslemos** [comment]
Because of style changes. Paddings can get bigger or smaller. Borders can get thicker or thinner. Typeface changes. Kerning. The possibilities are endless.

**Comment by mjhea0** [comment]
Do you have some examples of this that I can use to recreate on my end? When I change CSS (like borders, etc), the image is not changing size.

**Comment by esbenam** [comment]
Would like to see this break too (maybe as an option?). This can happen if you remove a part of a component or if you change a text.
