### ISSUE TITLE
Screenshot duplicates on a every test run

### ISSUE THREAD

**Issue by SchDen** [mjhea0/cypress-visual-regression#38]
I create a simple test and run him several times

Test code
```javascript
it('Load page corrctly', () => {
    cy.server();
    cy.route(/models\/\S+/).as('fetchMockData');

    cy.visit('/');
    cy.wait('@fetchMockData').its('status').should('eq', 200);

    cy.getByTestId('canvas').compareSnapshot('/compare/canvas');
});
```
All it's ok, but I saw in a project tree some screensots for this test
![image](https://user-images.githubusercontent.com/1484977/80223532-1326bc00-8651-11ea-8b4c-b27722919769.png)

When I try to call `cypress run` I got this message
```
  (Screenshots)

  -  /tests/e2e/screenshots/open-page.spe      (689x688)
     c.js/compare/canvas-actual.png  
```
and all files expect `canvas-actual.png` was deleted.

Cypress uses `canvas-actual.png` but a last generated file is `canvas-actual (2).png`. 

Could you please explain how it works?

**Comment by SchDen** [comment]
Also about additional files - `filename (1/2 ...).png` - can I  just add them to a .gitignore or I need call `cypress run` after every update my tests for removing these additional files?

**Comment by MattTreichelYeah** [comment]
@SchDen I have this same issue with duplicate filenames, but you closed this without mentioning a solution? 🤔

**Comment by SchDen** [comment]
Hi @MattTreichelYeah , I just moved to https://github.com/meinaart/cypress-plugin-snapshots. It's easier to use

**Comment by jaythomas** [comment]
Yeah except cypress-plugin-snapshots is no longer maintained and relies on you having a pretty old cypress version installed.
