### ISSUE TITLE
Plugin crashed

### ISSUE THREAD

**Issue by wow64ext** [mjhea0/cypress-visual-regression#39]
While running test on cypress 4.4.1 with cypress-visual-regression ^1.2.0 I'm getting following error:

The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`/Users/***/Repos/***-cypress/cypress/plugins/index.js`)

 Error: ENOENT: no such file or directory, open '/Users/***/Repos/***-cypress/cypress/snapshots/base/visual/***-eng-main.js/***-en-home-base.png'

**Comment by mjhea0** [comment]
Can you provide insight into your workflow? How are you running your tests?

**Comment by Tay08** [comment]
Hello @mjhea0 ,

I'm working with cypress-visual-regression and i've same difficulties to work my tests. 

Here is my workflow : 

I've configured support/commands.js 
```
const compareSnapshotCommand = require('cypress-visual-regression/dist/command');
 
compareSnapshotCommand();
```

And i've configured plugins/index.js 
```
const getCompareSnapshotsPlugin = require('cypress-visual-regression/dist/plugin');
 
module.exports = (on) => {
  getCompareSnapshotsPlugin(on);
};
```

Then, after have created my test "visual_testing.spec.js into "cypress/integration/examples" like this : 
```
describe('Integration test with visual testing', function () {
	it('Loads the homepage', function() {
		cy.visit('https://www.amazon.fr').then(() => {
			cy.compareSnapshot();
		})
	})
})
```

I run this cmd : `npx cypress run --spec cypress/integration/examples/visual_testing.spec.js --env type=base --config screenshotsFolder=cypress/snapshots/base`

It creates me a folder "snapshots/base/examples/visual_testing" where the .png file named "undefined-base.png" is included.

Then, i run this cmd : `npx cypress run --spec cypress/integration/examples/visual_testing.spec.js --env type=actual `

I get an error : 

> The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`/Users/<myuser>/Documents/Projects/Cypress-projects/cypress-visual-regression-plugin/cypress/plugins/index.js`)
> 
>  Error: ENOENT: no such file or directory, open '/Users/<myuser>/Documents/Projects/Cypress-projects/cypress-visual-regression-plugin/cypress/snapshots/base/examples/visual_testing.spec.js/undefined-actual.png'

And it creates me a folder "snapshots/diff/examples/visual_testing.spec.js" but is **empty**

Env : 
"cypress": "^4.4.0",
"cypress-visual-regression": "^1.2.0",

**Comment by mjhea0** [comment]
This should fix it: https://github.com/mjhea0/cypress-visual-regression/pull/40

Use version 1.3.1 of the library to test: https://www.npmjs.com/package/cypress-visual-regression

**Comment by Tay08** [comment]
Hi @mjhea0 
Thank you for your fix.
I allow myself to add this in the use of your plugin at the time of launching the script for the non regression. When launching the script, it's important to specify the directory like this: `cypress run --env type=actual --config screenshotsFolder=cypress/snapshots/actual`.  
No mentioned into your documentation https://www.npmjs.com/package/cypress-visual-regression. 
Unless, it works :) 
Simple question : How to custom the image name? I would like to have the combo "Test suite + context" for the image name. Ex : "Integration test with visual testing -- Loads the homepage.png"
