### ISSUE TITLE
pulgin crashes due to not able to find the actual.png file

### ISSUE THREAD

**Issue by ypatel26** [mjhea0/cypress-visual-regression#41]
the file location is /screenshots/actual.png, but the it's looking under /snapshot/actual/<spc.js>/actual.png.

Not sure what am i doing wrong.  I added file path in the cypress.json.
"env": {
    "screenshotsFolder":"./cypress/snapshots/actual",
    "trashAssetsBeforeRuns": true
  }

I'm on ios:

**Comment by mjhea0** [comment]
What does your full project structure look like?

**Comment by ypatel26** [comment]
<img width="299" alt="Screen Shot 2020-05-01 at 2 44 49 PM" src="https://user-images.githubusercontent.com/27960304/80832326-7026f280-8bba-11ea-90e3-255be2b9ff46.png">

**Comment by ypatel26** [comment]
Never mind now it works.  Not sure what happened before.  going to close the issue.
