### ISSUE TITLE
Compatibility with Typescript

### ISSUE THREAD

**Issue by StallionV** [mjhea0/cypress-visual-regression#43]
Are there any types available for Typescript compatibility?
I get an error when using this in VSCODE 

`Property 'compareSnapshot' does not exist on type 'cy & EventEmitter'.`

e.g.
```
it('Matches the snapshot', () => {
    cy.compareSnapshot('login', 0.0)
})
```

**Comment by mjhea0** [comment]
Sorry, no. Feel free to issue a PR.
