### ISSUE TITLE
Replace image-diff with pixelmatch?

### ISSUE THREAD

**Issue by jemerald** [mjhea0/cypress-visual-regression#5]
> image-diff is no longer actively maintained. Please use looks-same or pixelmatch instead

See https://www.npmjs.com/package/image-diff

**Comment by mjhea0** [comment]
Yes. It was deprecated in early 2017. I've been using it since mid 2017 with no issues. Great project. It works fine. 

LooksSame does look interesting though. I'm open to a PR if you want to add it in.

**Comment by jemerald** [comment]
Happy to raise a PR. I'm leaning towards pixelmatch though, because:
- higher npm usage and more github stars
- small in size and no dependency
- generates diff image in one call (`looks-same` requires separate call to generate diff)

**Comment by jemerald** [comment]
Got PR mostly working, except for one test that relies on the exact value for the "Normalized total difference" output from imagemagick

**Comment by mjhea0** [comment]
Why both pixelmatch and pngjs?

**Comment by jemerald** [comment]
pngjs is used to parse the image, pixelmatch to do comparison. See sample code on pixelmatch's README 
 https://github.com/mapbox/pixelmatch

**Comment by mjhea0** [comment]
I think I'm going to have to dig into this more. I have had zero problems with `image-diff` for the past 1.5 years, despite it being deprecated since early 2017. In fact, if it does move to `pixelmatch`, I'd probably fork it and maintain an `image-diff` flavor for production. 

Happy to chat more about this over a quick call if you're really set on `pixelmatch`.

**Comment by jemerald** [comment]
I'm not set one one library or another. Just didn't like the external dependency of ImageMagick, executing a command line app and parse its output seems flaky to me. And there's there deprecation notice.

But you are right, changing to any other library would almost certainly be a breaking change with regards to the difference percentage calculation. So would be better as a forked package instead.

**Comment by mjhea0** [comment]
I agree as well with the external dependency of ImageMagick. Want to re-write that failing test?

**Comment by jemerald** [comment]
I'm happy to rewrite the test.

This would mean a breaking change to existing consumer that makes use of the `errorThreshold` feature, I think we should bump the major version number.

**Comment by jemerald** [comment]
Test is now passing. I've changed the percentage calculation to be the squareroot of the percent difference, which yielded a value that's much closer to the one reported by ImageMagick, at least for your test scenario.

I've also added change log and bumped the version number (to v1 beta for now, just in case anymore breaking change is required)

**Comment by mjhea0** [comment]
Thanks! I'll take a look at it later today.

**Comment by mjhea0** [comment]
Just bumped cypress to the latest version. I'm going to pull off the beta tag.
