### ISSUE TITLE
My test always pass

### ISSUE THREAD

**Issue by travis5491811** [mjhea0/cypress-visual-regression#57]
My test always pass.

```
describe.only('Visit Home - snapshot testing', () => {
   before(() => {
      cy.viewport(2000, 1500)
      cy.visit(url)
   })

   it('Visits the home page', () => {
      cy.viewport(2000, 1500)

      cy.contains('footer', 'Need Help') // adding delay to wait till this is visible

      cy.compareSnapshot('homePage', 0.0)

      cy.scrollTo('0%', '0%') // scroll back to top
      // see
      // https://github.com/cypress-io/cypress/issues/871
   })
})
```

```
//cypress.json
{
   "video": false,
   "screenshotOnRunFailure": false,
   "screenshotsFolder": "./cypress/snapshots/actual",
   "trashAssetsBeforeRuns": true,
   "env": {
      "failSilently": false
   }
}
```

```
//commands.js
const compareSnapshotCommand = require('cypress-visual-regression/dist/command')

compareSnapshotCommand()
```

```
//cypress/plugins/index.js
const getCompareSnapshotsPlugin = require('cypress-visual-regression/dist/plugin')

module.exports = (on) => {
   getCompareSnapshotsPlugin(on)
}
```

In the above example, the first run it takes snapshot as expected. Then i change something (added text) on the home page and re-run. The test re-runs and passes. When i look at the screenshots, `homePage-actual.png` is different than `homePage-actual (1).png` but it passed.

I also tried 
```
cy.compareSnapshot('homePage', 0.0)
cy.compareSnapshot('homePage', 0.1)
```

I am running with
```
    "cypress": "./node_modules/.bin/cypress open",
    "cypress-check": "./node_modules/.bin/cypress open --env type=actual",
```

I want the test to fail if anything is different. What am i missing?

**Comment by mjhea0** [comment]
You need to run it once with a type of `base` in order to create the base, pristine snapshots to compare against:

```sh
./node_modules/.bin/cypress run --env type=base --config screenshotsFolder=cypress/snapshots/base
```

**Comment by lucidity-joe** [comment]
@mjhea0 I'm having the same issue except I already have my base files, and I've set the threshold to 0. Are there any other possible problems that could cause this?

**Comment by lucidity-joe** [comment]
Immediate follow up: I have managed to trigger a failing test but the only way to do it seems to be to run:

"./node_modules/.bin/cypress run --env type=actual"

Is there no way to have the normal tests run regression? Or is there a way to trigger the above without running all my tests that don't do visual regression?

**Comment by gibbok** [comment]
In package.json you can create your own script and call it example:

```json
 "scripts": {
    "visual:base": "./node_modules/.bin/cypress run --env type=base --config screenshotsFolder=cypress/snapshots/base
}
```

and use it as:

```bash
npm run visual:base
```

**Comment by lucidity-joe** [comment]
@gibbok This is essentially what I ended up doing to solve this issue. I just thing the documentation could be a bit clearer about the need to pass in type=base and type=actual every time, and there not seeming to be a default.

**Comment by gibbok** [comment]
@lucidity-joe thanks for your comment, yes actually I agree the docs could be improved 😄 
How do you find a regression?
Currently I am adding this script

```
"visual": "./node_modules/.bin/cypress run --env type=actual"
```

do you check if the diff folder created has some files using bash or similar or is it possible to do it in JS within the cypress tests?

Or should I use this function?
https://github.com/mjhea0/cypress-visual-regression/blob/286c566ac254d42ad8b5f91e154d3cee409ce3c0/docker/cypress/support/commands.js

**Comment by mjhea0** [comment]
> @gibbok This is essentially what I ended up doing to solve this issue. I just thing the documentation could be a bit clearer about the need to pass in type=base and type=actual every time, and there not seeming to be a default.

Feel free to open a PR for this. :)

**Comment by jarretmoses** [comment]
I have been falling into the same issue. If I am following this thread correctly does this library not do a diff on its own using the `compareSnapshot` command and thus I need to use a `.expect`?
