### ISSUE TITLE
compareSnapshotsPlugin  doesn't work when setting screenshotsFolder with non-default path

### ISSUE THREAD

**Issue by Renaud009** [mjhea0/cypress-visual-regression#64]
compareSnapshotsPlugin fails without any error when screenshot folder is not the same as cypress default (/cypress/snapshots)
{
  "screenshotsFolder": "./src/snapshots/actual", // nx suggested path
  "env": { "type": "actual" }
}

Same error as if there's not actual baseline images to compare to "- then      function(){}":
![image](https://user-images.githubusercontent.com/14914217/99314055-816dde80-282e-11eb-88b2-3ab4de8b43ca.png)

Note that diff folder is always cypress/snapshots/diff whatever is provided to screenshotsFolder variable

**Comment by mjhea0** [comment]
Is this still an issue @Renaud009?

**Comment by Renaud009** [comment]
No, actually it was my mistake, the second param to getCompareSnapshotsPlugin was missing.
We need to pass both **on** and **config** to getCompareSnapshotsPlugin(on, config) or the cypress configuration is.. of course ignored by the plugin.
