### ISSUE TITLE
Actuals have different aspect ratios to base images with no discernible reason why

### ISSUE THREAD

**Issue by lucidity-joe** [mjhea0/cypress-visual-regression#70]
I am having a lot of issues with this plugin but the most frustrating by far is this. If I run with type=base then type=actual, with no other difference between the commands this issue still occurs:

The aspect ratios of the images taken for base and actual runs are different and causing the actual runs to fail when they should not.

I'll upload two snapshots below taken on identical runs besides the type being actual or base:

Base image (2212x1566):
![billing-base](https://user-images.githubusercontent.com/68896248/100726569-06273380-33bd-11eb-9e78-6496eb1ef189.png)

Actual image (2732x1574):
![billing-actual (1)](https://user-images.githubusercontent.com/68896248/100726660-23f49880-33bd-11eb-9b84-aa1349fde34f.png)

Please let me know what I'm supposed to do to avoid this happening. Is there somewhere I can specify the aspect ratio/pixels/size of the snapshot images?

**Comment by mjhea0** [comment]
The plugin works on top of the Cypress [screenshot](https://docs.cypress.io/api/cypress-api/screenshot-api.html) API, so you'll need to experiment with it. You can pass [arguments](https://docs.cypress.io/api/cypress-api/screenshot-api.html#Arguments) to the command like so:

```js
compareSnapshotCommand({
  capture: 'fullPage'
});
```

There are a number of open issues that deal with your concerns. Check out https://github.com/cypress-io/cypress/issues/3324.
