### ISSUE TITLE
Enhancement: hide Chromatic ignored elements (or more globally elements based on a selector)

### ISSUE THREAD

**Issue by eric-burel** [mjhea0/cypress-visual-regression#81]
Hi, small enhancement suggestion: I've setup cypress-visual-regression, so it also respects [Chromatic ignored elements](https://www.chromatic.com/docs/ignoring-elements), for those who also use Storybook for visual regression testing at the unit level.

Here is the command I've created: it overrides `compareSnapshot` with a "before" step that removed selected elements from the page.

```js
/**
 * To be called after you setup the command, in order to add a
 * hook that does stuff before the command is triggered
 */
function beforeCompareSnapshotCommand(
  /** Element you want to ignore */
  ignoredElementsQuerySelector: string,
  /** Main app element (if you want for the page to be loaded before triggering the command) */
  appContentQuerySelector: string = "body"
) {
  Cypress.Commands.overwrite("compareSnapshot", (originalFn, ...args) => {
    // wait for content to be ready
    // NOTE: be sure you wait enough so that all elements are correctly present
    return cy
      .get(appContentQuerySelector)
      .then($app => {
        return new Cypress.Promise((resolve, reject) => {
          setTimeout(() => {
            $app.find(ignoredElementsQuerySelector).css("visibility", "hidden");
            resolve();
            // add a very small delay to wait for the elements to be there, but you should
            // make sure your test already handles this
          }, 300);
        });
      })
      .then(() => {
        return originalFn(...args);
      });
  });
}

module.exports = beforeCompareSnapshotCommand;
```

Usage:
```js
const compareSnapshotCommand = require("./commands/compareSnapshots"); //require("cypress-visual-regression/dist/command");
const beforeCompareSnapshotCommand = require("./commands/beforeCompareSnapshots"); //require("cypress-visual-regression/dist/command");
compareSnapshotCommand({
  errorThreshold: 0.1
});
// add a before hook to compareSnapshot (this must be called AFTER compareSnapshotCommand() so the command can be overriden)
beforeCompareSnapshotCommand(
  ".chromatic-ignore,[data-chromatic='ignore']",
  "._app-content"
);
```

Could this be added somewhere in the doc? It can be done in user-land, so no need to update the library.

Edit: ~small limitation, it expects some elements to be hidden, I am reworking it a bit. It has to add some delay to the screenshot, because we need to wait for the element to be hidden, I haven't yet found an optimal way.~ Updated the code so it works even if you have nothing to hide.

It would be a good practice to always wait for all relevant elements to be there before screenshotting, so we can safely remove the things that should be hidden.

**Comment by mjhea0** [comment]
This sounds good. Would you like to open a PR?

**Comment by eric-burel** [comment]
this would mostly be a documentation PR, do you think this would fit somewhere at the end of the Readme, in an new "Do something before the screenshot" section for instance or "Tips and tricks"?

**Comment by mjhea0** [comment]
"Tips and Tricks" sounds good at the end of the README. Thanks!
