### ISSUE TITLE
Can't get the compareSnapshot to ever fail

### ISSUE THREAD

**Issue by dariuszteooh** [mjhea0/cypress-visual-regression#83]
Hi folks, 

I followed the steps in your readme, added a `"failSilently": false` to the "env" section of my cypress.json, even tried passing this parameter in compareSnapshotCommand, no luck. I just can't ever get the tests to fail. I even tested this by taking a base image of one page, then edited the test to navigate to a different page and still try to compare it, and it doesn't fail even if the page is completely different. My test looks like this: 
`it('Login page visual regression', () => {
                cy.visit('/login')
                cy.compareSnapshot('login-page')
            })`

I even verified manually that the images in base folder are completely different to those in actual folder. 

Any ideas? I'd appreciate your help on this. 

Thanks,
Dariusz

**Comment by mjhea0** [comment]
@dariuszteooh which commands are you running?

**Comment by dariuszteooh** [comment]
@mjhea0 thanks for getting back to me. Which commands exactly do you mean? I've pasted a code snipped of my test. Is that not what you mean here? 
I start the test with 
`./node_modules/.bin/cypress run --env configFile=build,imageComparisonRun=true --spec \"cypress/integration/visual_regression/visual_regression_tests.js\"`

Inside my test I only use cy.compareSnapshot('name)

Thanks

**Comment by mjhea0** [comment]
You first have to get the base images:

```sh
cypress ./node_modules/.bin/cypress run --env type=base --config baseUrl=http://127.0.0.1
```

Then you can take the new images and compare them with the base to find regressions:

```sh
cypress ./node_modules/.bin/cypress run --env type=actual --config baseUrl=http://127.0.0.1
```

**Comment by dariuszteooh** [comment]
Ah, I think you're right. You see, I did have the base images, but then I was running the tests without the **_type_** set to actual, just wasn't passing this parameter at all. I've done that now and it looks correct. 

Thanks a lot for the help, I appreciate the quick response.
