### ISSUE TITLE
Small differences in scolling cause the tests to fail 

### ISSUE THREAD

**Issue by dariuszteooh** [mjhea0/cypress-visual-regression#88]
Hi,

I'm running the tests on a website that's quite long so even in a viewport of 1920x1080 needs to be scrolled down quite a bit. The problem is, the scrolling speed or distance seems to differ ever so slightly between the tests, causing them to fail. 
Here's an example. The page is https://roomkey.co/creating-a-room/

Excuse the large images. 

This is the base image: 
![create-a-room-page-base](https://user-images.githubusercontent.com/64851760/125057799-87584e80-e0a1-11eb-9371-bd4920aeafae.png)
This is a screenshot taken in the test: 
![create-a-room-page-actual](https://user-images.githubusercontent.com/64851760/125057859-97702e00-e0a1-11eb-8f1d-c99dc18aca7d.png)
And finally, the diff: 
![create-a-room-page-diff](https://user-images.githubusercontent.com/64851760/125057886-9d660f00-e0a1-11eb-80e2-81c0d3e35cd2.png)
As you can see, there are small differences in how far the scroll has moved and that breaks the test. It's intermittent, too. 

Any ideas on how to fix that?

**Comment by mjhea0** [comment]
Have you tried increasing the error threshold?

**Comment by dariuszteooh** [comment]
As you can see, the differences in scrolling make the diff quite
significant, so increasing the threshold high enough to ignore that will
just render the tests useless, as they won't pick up actual changes.

**Comment by mjhea0** [comment]
Why are you testing the full page? I would isolate it to specific elements. The larger the image, the greater the chance something like this is going to happen.

I'm going to close this since it's unrelated to the tool.

**Comment by bmaupin** [comment]
If I'm not mistaken, this seems to be an issue with Cypress itself and how it takes screenshots: https://github.com/cypress-io/cypress/issues/2681
