### ISSUE TITLE
utils-browser.js is missing in /dist folder in release 1.5.10

### ISSUE THREAD

**Issue by amuttsch** [mjhea0/cypress-visual-regression#96]
The latest version is missing the `utils-browser` file in the `dist` folder from the npm package. This leads to the following error when trying to execute any Cypress tests:

```
Error: Webpack Compilation Error
./node_modules/cypress-visual-regression/dist/command.js
Module not found: Error: Can't resolve './utils-browser' in 'node_modules/cypress-visual-regression/dist'
```

![image](https://user-images.githubusercontent.com/5488288/127451874-b0c8d85d-c161-4b0a-8044-72258e32699e.png)

I guess sth. went wrong while building / bundling the release. Can you please publish a new version with the file included? Thanks!

**Comment by mjhea0** [comment]
https://github.com/mjhea0/cypress-visual-regression/pull/95
